### ISSUE TITLE
[Feature Request] Hide all tabs except those in current group

### ISSUE THREAD

**Issue by Hondoe1950** [projectdelphai/panorama-tab-groups#118]
All of the tabs in all of the groups are shown at the top of the screen.

Once this number gets pretty high, that's completely useless and cluttered.

Adding a toggle to hide all of the tabs except those in the selected group would be a wonderful feature.

Yes?

**Comment by vaxul** [comment]
This might be a duplicate #72

**Comment by projectdelphai** [comment]
Closing as this doesn't make any sense at all and we'll need more context on the issue. If you mean in the normal view, you *shouldn't* see any tabs other than the active group. If you are, then something is wrong. If you mean in the panorama view page, then you want to see all the groups so that you can switch between them. If you want something close to #72 and I misunderstood you, then this is a duplicate anyways and can be closed.
