### ISSUE TITLE
any plans for chrome extension?

### ISSUE THREAD

**Issue by lokesh1729** [projectdelphai/panorama-tab-groups#124]
Hey,

I really like the extension and enjoyed using it. I am using one-tab for chrome, but that is not much friendly than this... so, is there any plan to write a chrome extension ???

**Comment by projectdelphai** [comment]
I looked into this briefly and the main problem is that Chrome doesn't support a tab hiding API. So instead of an almost drop and go extension, I would have to recode PTG to close and open tabs (instead of hiding them). Which isn't that bad of an alternative, but definitely subpar since you'd have to wait for each tab group to load which would be a lot slower when group switching.

So probably won't be coming for a long while. Especially considering all the work I'd have to do to convert when there's big features in PTG coming that I want to do first (i.e automatic grid layout, search etc)
