### ISSUE TITLE
Extension broken

### ISSUE THREAD

**Issue by orval** [projectdelphai/panorama-tab-groups#156]
I hit the import failure so installed master (2019-09-24). The toolbar button doesn't work so the whole thing is unusable. Errors in the console:

```
Initializing Panorama Tab View background.js:416:5

Webconsole context has changed

Error: Type error for parameter details (Unexpected property "windowId") for browserAction.setTitle. background.js:355:5

Error: Type error for parameter createProperties (Unexpected property "discarded") for tabs.create. backup.js:140:20
```

**Comment by projectdelphai** [comment]
Thanks for letting me know, I'll take a look when I get home later today. I pushed a couple commits over the past week so that might have broken it although it works for me.

Just a reminder that master is not guaranteed to be release state so there may be bugs or missing features in it.

On to debugging, what platform and environment are you using? Please provide OS, hardware (if unusual), and Firefox version. browserAction.setTitle() using windowId relies on Firefox version 62 at least (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setTitle) so if you're running anything before then, that's why it won't work. 

browser.tabs.create() using the discarded property relies on firefox version 63 (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create) to work so I'm starting to think it might just be that you're using an older version of Firefox. Is that true?

If so, the only way to fix it will be to upgrade.

**Comment by orval** [comment]
I’m using v61. It’s the only version I have access to. (I work in a heavily regulated environment.)
I have been using PTG fine until a couple of days ago. I guess I’ll try going back to 0.8.9 but I lost all my groups for some reason which is why I’m trying to restore from backup.

**Comment by projectdelphai** [comment]
I can definitely put in an option to disable the setTitle option which might fix that option. I'll need to reread the code for the discarded property to see if there's a way to make that optional for you as well.

**Comment by orval** [comment]
I switched to a new machine and I'm now using FF dev edition 71.0b4. I don't have the issue described here any more.

**Comment by oaken-source** [comment]
Just ran into this problem with firefox ESR. If what has been written here is correct, then the information claimed on the plugins website in the mozilla store is misleading:

"Works with firefox 42.0 and later"
