### ISSUE TITLE
Tab groups missing and can no longer double-click to create

### ISSUE THREAD

**Issue by serendipiddy** [projectdelphai/panorama-tab-groups#169]
Auto-updated today to find it the tabs groups a little broken. Several of my groups were missing from the tab groups view.. however i could navigate to them.

The names of the groups was no longer correct, having swapped around arbitrarily.

I was also unable to double click to create a new tab group for a time. After closing and reopening my browser I was able to create new ones.. but they became unselectable and smooshed into the top left corner

I tried exporting/importing my tab groups and re-importing it.. this put a group (or several) in the top left corner, but i could not select them. sigh. reverted back to previous version.. this was not a fun thing to deal with unexpectedly.

**Comment by reykjalin** [comment]
I'm having what seems to be the same issue. 2 of my tab groups are missing, however I can navigate to them using `Alt + W`.

The UI itself also seems broken. I'm only able to move and resize 1 of my remaining tab groups around. Since the "missing" tab groups seem to be squished into the top left corner this becomes a problem, since I can't resize the groups or move them around.

This makes me wonder if this is related to the new tiling feature? The buttons at the top that I assume are for turning that on/off don't work. I can't even click the settings wheel when I open the tab groups view.

If there's a way to somehow turn off the tiling through a config file to test this, that would be great :)

**Comment by projectdelphai** [comment]
Don't worry, it happened to me too :/ Doesn't appear to be the tiling feature, it actually appears to be a small change that was supposed to reorder group ids if you deleted groups. Undid that change and pushed a new patch. Once it's approved, hopefully it fixes it for us. It doesn't seem to affect new installations at all which is why it wasn't popping up in my tests. But for complicated old setups (like ours), it just seriously messes it up. Lesson learned, going to have to try and figure out a test for cases like this.

**Comment by projectdelphai** [comment]
Looks like the latest update was just approved and it automatically fixed my setup. Please update your addon manually and confirm if it works. I'll stay up a little bit if I can to make sure that it helped you guys, but I do have to sleep for work :(.Hopefully that helps you guys out and I didn't end up breaking anyone else's set up.

**Comment by reykjalin** [comment]
Everything seems to be working for me with the new update. Thank you for getting the fix up so quickly! 🎉

**Comment by projectdelphai** [comment]
👍 Thanks for confirming. Had to take a blind guess as to which commit was the broken one because if I started a new firefox session with any changes, there's was no bug. It would only affect my main personal firefox setup and I can't make changes there. Gotta figure out something better later, but problem for another day. Glad to hear it worked for you.

Time to sleep 😴

**Comment by serendipiddy** [comment]
Upgraded again.. and things seem to be behaving this time :smiley_cat: No missing groups, groups have the correct name, can create new groups by double clicking on an empty space.. restarted browser and it's still behaving.

Given i recreated my groups from scratch after reverting to the previous version, i'm unsure if this is representative of the previous tab groups, but definitely seems like an improvement!

Thank you so much for the quick response/late night to fix this :)
