### ISSUE TITLE
Alt-W issue

### ISSUE THREAD

**Issue by udovdh** [projectdelphai/panorama-tab-groups#17]
Same issue as described at https://github.com/photodiode/panorama-view/issues/42
Bascially: I have to press Alt-W N+1 times to get back to the same tab group I started from.
I am expecting to press Alt-W just N times.

**Comment by projectdelphai** [comment]
Did you do the same debugging I recommended for your other issue? I'm trying it on my browser and it doesn't seem to be an issue for me. I get it the first time with the lastpass extension, but I disabled that and that seemed to fix it. It's likely that you might have an add-on that creates another tab and that's why you cycle through the last group twice.

 1. Go to about:profiles and create a new profile
 1. Under your new profile, click the option to "Launch profile in a new browser"
 1. Download the panorama-view to your computer
 1. Go to about:debugging and click "Load Temporary Add-on"
 1. Load the manifest.json file in the src folder from this project

You can open debugging there and see the logs too when you you reproduce the error and see if you can figure out what you need to do break it so I can try and fix it.

**Comment by Instagit** [comment]
I think the problem here is that ALT+W also toggles through empty groups, but there's no visual feedback.

So if you have 4 groups like this: 

[0] 2 open tabs
[1] 2 open tabs
[2] 0 open tabs
[3] 0 open tabs

When you're in group [1] and press ALT+W, you move to tab [2], but don't see any changes. Same for [3]. So to get from [1] to [0], you need three actions, but two of those don't do anything and that makes it very unintuitive.

I suggest skipping empty groups to avoid this.

**Comment by udovdh** [comment]
At this time (FF 66.0.2, PTG 0.8.8) I cannot reproduce the original issue... (!!) :-)
