### ISSUE TITLE
New shortcut "Activate the nth Tab Group"

### ISSUE THREAD

**Issue by DatGrey** [projectdelphai/panorama-tab-groups#173]
As title suggests, would it be possible to add a shortcut that activates a certain group directly? Thanks.

**Comment by projectdelphai** [comment]
I don't think so. I can't think of a way that would scale properly because there a potentially unlimited amount of groups and deciding how to do that doesn't seem like it would work. Unless you said you could specify shortcuts for only 5 groups and then people would ask why not 10. or 5 is too many. And generally finding shortcuts is hard since there's so much overlap with other functionality.

**Comment by DatGrey** [comment]
That makes sense; what about a "go to the first group" shortcut? That way we would have a way to use a group as "primary" and quickly go back to it if needed.

**Comment by vaxul** [comment]
The problem with the current freeform view is, that no sorting of groups exists. The primary group would always be the "oldest" group. 

Might be okay.

Sidenode: With the new popup view from my pull request, it is possible sort the groups. This would influence the sorting globally.
