### ISSUE TITLE
Can't import from Panorama View

### ISSUE THREAD

**Issue by gaekwad** [projectdelphai/panorama-tab-groups#2]
Decided to check this branch out after you fulfilled my request for a previous group keyboard shortcut (also having the shortcuts customizable), but it looks like I can't import my groups from Panorama View? Is this extension's group format not compatible with Panorama View?  After I click the import button and select the json file, nothing appears to happen.  Doing the same in the original Panorama View, it opens a new window with my groupings.  (Although, in the groupings view, it's screwed up with the groups invisible and on top of each other in the upper left corner).

**Comment by projectdelphai** [comment]
I haven't changed any code yet except to allow you to drag a tab outside of a group to create new groups and to refactor how keyboard shortcuts work. So if it didn't work I'm not sure why except to think that importing/exporting might not work in general (or it doesn't work between different addons).

I can look into it, but tbh I'm not sure why it wouldn't work since the code should be exactly the same so I might think that just redoing your groups in Panorama Tab Groups would be best

**Comment by gaekwad** [comment]
Glancing through your code, I believe it's because you removed the listeners for the load and save backup buttons in options.js, they used to be in the init function there.

**Comment by udovdh** [comment]
I would like to try this version of the addon so working import/export would be very helpful!

**Comment by projectdelphai** [comment]
hm . . . I didn't even realize I did that. I should be more careful in the future. Thanks for letting me know! I'll update that as soon as I can.

**Comment by projectdelphai** [comment]
@udovdh I realized what happened when i went to fix it, I accidentally deleted the whole init function because I was rewriting how keyboard shortcuts worked and I didn't realize the last couple lines were not related to commands. It should work now if you try it (either through the project code or via the Firefox add-on installation).

Please let me know if there's anything else wrong and I'll try not to let it happen again :)

**Comment by gaekwad** [comment]
@projectdelphai thanks, it looks like it works now. I've switched to this addon for now :)

**Comment by projectdelphai** [comment]
Closing this issue as it looks like it's fixed
