### ISSUE TITLE
Send to Group - Multiple tabs?

### ISSUE THREAD

**Issue by Sada-Mio** [projectdelphai/panorama-tab-groups#99]
Is there a way to send multiple tabs with the "Send to Group" context menu?

Holding [ctrl] I can select multiple tabs, but "Send to Group" only sends 1 tab.

**Comment by projectdelphai** [comment]
This is one of the pain points for me too, I just need to find out how to get all selected tabs and then loop through them and send to group. Shouldn't be that hard as long as there's a function call for it. I'll let you know.

**Comment by Sada-Mio** [comment]
https://github.com/projectdelphai/panorama-tab-groups/issues/25#issuecomment-440733153

piroor, comment a possible hint?

**Comment by projectdelphai** [comment]
This should be done now and is pushed to master. Will come out with the next version. Slight complexity: when selecting multiple tabs, the active tab is selected as well whether you like it or not. I've changed it so that when selecting multiple tabs to move, the active tab is never moved. Just so people don't get confused whether their tab went. So slight quirkiness, but it works overall
